lcserver: adjust handling of application/json POST data
The python3 cgi module has issues parsing application/json
data. It doesn't support it at all, and will give
unicode errors when processing the data, like this:
  File "/home/tbird/test/test-json-form.py", line 7, in app
    form = cgi.FieldStorage()
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes

Handle this application/json data myself with my own class, to
avoid these problems.

Signed-off-by: Tim Bird <tim.bird@sony.com>